image: haskell:8.6.5

before_script:
  - apt-get update && apt-get install -y libpcre2-dev libpcre3 libpcre3-dev

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack-root"

cache:
  paths:
    - .stack-work/
    - .stack-root/

test:
  stage: test
  script:
    - ghc --version
    - stack test

