name:                owwica
version:             0.0.22
#synopsis:
#description:
homepage:            https://github.com/agander/owwica#readme
github:              agander/owwica
license:             GPL-3
author:              A Anderson
maintainer:          agander@gmail.com
copyright:           2018 A Anderson
category:            Student
extra-source-files:
  - README.md

dependencies:
  - base             >= 4.7 && < 5
  - split            >= 0.2.3
  - directory        >= 1.3.0.0
  - regex-pcre
  - hspec            == 2.*
  - QuickCheck
  - filepath         >= 1.4.1
  - text             >= 1.2.2.2
  - bytestring       >= 0.10.8.1
  - hledger-lib
  - base-prelude
  - io-streams       >= 1.5.1.0
  - zlib             >= 0.6.2

default-extensions:
- OverloadedStrings

library:
  source-dirs: src
  exposed-modules:
  - Lib
  dependencies:
  - base >=4.7 && <5
  - directory >=1.3.0.0

executables:
  owwica:
    source-dirs:      app
    main:             Main.hs
    dependencies:
      - owwica
      - filepath >=1.4.1
      - text >=1.2.2.2
      - cmdargs >=0.10.20
      - bytestring >= 0.10.8.2
    ghc-options:
    - -Wall
    - -fno-cse
    - -rtsopts
    - -fprint-potential-instances    

#  str_to_text:
    #source-dirs:      ./
    #main:             str_to_text.hs
    #dependencies:
##     - str_to_text
      #- filepath >= 1.4.1
      #- text >=1.2.3.0
      #- time >= 1.8.0.2
##     - cmdargs >= 0.10.20
    #ghc-options:
    #- -Wall
    #- -fno-cse
    #- -rtsopts
    #- -fprint-potential-instances    

  #str_to_bytestr:
    #source-dirs:      ./
    #main:             str_to_bytestr.hs
    #dependencies:
##     - str_to_text
      #- filepath >= 1.4.1
##      - text >=1.2.3.0
      #- time >= 1.8.0.2
      #- bytestring >= 0.10.8.2
      #- owwica
    #ghc-options:
    #- -Wall
    #- -fno-cse
    #- -rtsopts
#    - -fprint-potential-instances    

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
      - app
    dependencies:
      - owwica
      - hspec == 2.*
      - QuickCheck
      - temporary
      - mockery >= 0.3
      - interpolate
      - HUnit >= 1.6.0.0

build-tools: hspec-discover

